version: '3'

services:
  reviews:
    build: .
    depends_on:
      - 'database'
    ports:
      - '80:3003'
    environment:
      - NR_LICENSE=
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=

  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - '27017:27017'
