version: '3'

services:
  reviews:
    build: reviews/
    depends_on:
      - 'database'
    ports:
      - '3003:3003'

  nearby:
    build: nearby/
    depends_on:
      - 'database'
    ports:
      - '3004:3004'

  proxy:
    build: proxy-Oliver/
    depends_on:
      - 'database'
    ports:
      - '3000:3000'
    image: node:latest

  database:
    image: mongo:latest
