version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
      - image: circleci/mongo:3.4.4
      - image: circleci/redis

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run seed-test:mongo
      - run: npm test
