version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
        environment:
          PGHOST: 127.0.0.1
          PGDATABASE: circle_test
          PGUSER: circleci-demo-go
      - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run seed-test:mongo
      - run: npm test
